# Generated by Django 2.0.4 on 2018-04-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='observacao',
            field=models.CharField(default='', max_length=255),
        ),
    ]
