# Generated by Django 2.0.4 on 2018-04-23 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_observacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='observacao',
        ),
    ]
