# Generated by Django 2.1.7 on 2019-03-03 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_auto_20190302_0322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='descrition',
            new_name='description',
        ),
    ]
